const Restaurants = [
  {
    restaurant_id: "1234",
    restaurant_name: "The Spice House",
    cuisine: ["Indian", "Chinese"],
    rating: 4.5,
    delivery_time: "30-40 minutes",
    price_range: "₹₹",
    address: "123, MG Road, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "1001",
        item_name: "Paneer Butter Masala",
        price: "₹350",
        description: "Delicious paneer cooked in rich, creamy gravy.",
        available: true,
      },
      {
        item_id: "1002",
        item_name: "Chicken Biryani",
        price: "₹400",
        description: "Aromatic biryani made with tender chicken.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "5678",
    restaurant_name: "Burger King",
    cuisine: ["Fast Food", "American"],
    rating: 4.0,
    delivery_time: "20-30 minutes",
    price_range: "₹₹",
    address: "456, Church Street, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "2001",
        item_name: "Whopper Burger",
        price: "₹250",
        description: "Juicy beef patty with fresh veggies and sauces.",
        available: true,
      },
      {
        item_id: "2002",
        item_name: "French Fries",
        price: "₹100",
        description: "Crispy golden fries.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "91011",
    restaurant_name: "Pizza Hut",
    cuisine: ["Italian", "Pizza"],
    rating: 4.2,
    delivery_time: "40-50 minutes",
    price_range: "₹₹₹",
    address: "789, Bannerghatta Road, Bangalore, Karnataka",
    is_open: false,
    menu: [
      {
        item_id: "3001",
        item_name: "Pepperoni Pizza",
        price: "₹600",
        description: "Thin crust pizza topped with pepperoni and cheese.",
        available: false,
      },
      {
        item_id: "3002",
        item_name: "Cheese Burst Pizza",
        price: "₹750",
        description: "Pizza with extra cheese in the crust.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "1213",
    restaurant_name: "Tandoori Express",
    cuisine: ["Indian", "North Indian"],
    rating: 4.3,
    delivery_time: "25-35 minutes",
    price_range: "₹₹₹",
    address: "101, Richmond Road, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "4001",
        item_name: "Tandoori Chicken",
        price: "₹300",
        description: "Marinated chicken grilled to perfection.",
        available: true,
      },
      {
        item_id: "4002",
        item_name: "Naan",
        price: "₹50",
        description: "Soft, warm, and fluffy flatbread.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "1415",
    restaurant_name: "Sushi World",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.8,
    delivery_time: "45-55 minutes",
    price_range: "₹₹₹",
    address: "202, Ulsoor Road, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "5001",
        item_name: "California Roll",
        price: "₹550",
        description: "Crab, avocado, and cucumber in a sushi roll.",
        available: true,
      },
      {
        item_id: "5002",
        item_name: "Salmon Nigiri",
        price: "₹400",
        description: "Fresh salmon on vinegared rice.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "1617",
    restaurant_name: "Pasta House",
    cuisine: ["Italian", "Pasta"],
    rating: 4.1,
    delivery_time: "30-40 minutes",
    price_range: "₹₹₹",
    address: "303, Indiranagar, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "6001",
        item_name: "Spaghetti Carbonara",
        price: "₹500",
        description: "Classic Italian pasta with creamy sauce.",
        available: true,
      },
      {
        item_id: "6002",
        item_name: "Penne Arrabbiata",
        price: "₹450",
        description: "Spicy pasta with tomato sauce and garlic.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "1819",
    restaurant_name: "The Healthy Bowl",
    cuisine: ["Healthy", "Salads", "Vegan"],
    rating: 4.7,
    delivery_time: "20-30 minutes",
    price_range: "₹₹",
    address: "404, Koramangala, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "7001",
        item_name: "Quinoa Salad",
        price: "₹350",
        description: "A healthy mix of quinoa, veggies, and dressing.",
        available: true,
      },
      {
        item_id: "7002",
        item_name: "Acai Bowl",
        price: "₹400",
        description: "Acai berries with fruits and granola.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "2021",
    restaurant_name: "The Seafood Shack",
    cuisine: ["Seafood", "Indian"],
    rating: 4.4,
    delivery_time: "30-45 minutes",
    price_range: "₹₹₹",
    address: "505, Whitefield Road, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "8001",
        item_name: "Fish Curry",
        price: "₹400",
        description: "Traditional Indian fish curry with spices.",
        available: true,
      },
      {
        item_id: "8002",
        item_name: "Prawn Masala",
        price: "₹500",
        description: "Succulent prawns cooked in a rich masala.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "2223",
    restaurant_name: "Café Mocha",
    cuisine: ["Cafe", "Italian", "Beverages"],
    rating: 4.0,
    delivery_time: "15-25 minutes",
    price_range: "₹₹",
    address: "606, Jayanagar, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "9001",
        item_name: "Cappuccino",
        price: "₹150",
        description: "Classic Italian coffee with a creamy froth.",
        available: true,
      },
      {
        item_id: "9002",
        item_name: "Cheese Croissant",
        price: "₹120",
        description: "Flaky croissant filled with cheese.",
        available: true,
      },
    ],
  },
  {
    restaurant_id: "2425",
    restaurant_name: "The Veggie Delight",
    cuisine: ["Vegetarian", "Indian", "Vegan"],
    rating: 4.6,
    delivery_time: "25-35 minutes",
    price_range: "₹₹",
    address: "707, BTM Layout, Bangalore, Karnataka",
    is_open: true,
    menu: [
      {
        item_id: "10001",
        item_name: "Vegetable Biryani",
        price: "₹350",
        description: "Aromatic biryani with mixed vegetables.",
        available: true,
      },
      {
        item_id: "10002",
        item_name: "Aloo Gobi",
        price: "₹220",
        description: "Potatoes and cauliflower in a spiced gravy.",
        available: true,
      },
    ],
  },
];
export default Restaurants;
